apiVersion: v1
kind: Pod
metadata:
  name: sns-incoming-operator-messages-converter
spec:
  containers:
  - image: sns-incoming-operator-messages-converter:0.1.1
    name: sns-incoming-operator-messages-converter
    imagePullPolicy: Never
    env:
      - name: KAFKA_BROKER_SERVER
        valueFrom:
          configMapKeyRef:
            name: kafka-broker-config
            key: KAFKA_BROKER_SERVER
      - name: KAFKA_BROKER_PORT
        valueFrom:
          configMapKeyRef:
            name: kafka-broker-config
            key: KAFKA_BROKER_PORT